Repository M1zz/RelaxOn, pull requests merged in 2022-08, with the labels that each got.

#142 [refactor] #141 CDLibraryView 위치를 View 폴더 내부로 이동
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Views/Home/CdLibraryView.swift
Labels: refactor

#145 [feat] SelectedImage 백그라운드 및 앨범 커버 공용 컴포넌트 제작
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Views/Kitchen/SelectedImageBackgroundView.swift
  RelaxOn/Views/Kitchen/SelectedImageVew.swift
  RelaxOn/Views/Kitchen/StudioNamingView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Kitchen/TestNavigateView.swift
Labels: feature

#144 [fix] 콘솔창에 뜨는 warning 제거
  RelaxOn/Views/Home/CdLibraryView.swift
Labels: fix

#140 [Feat] #124 remoteController & background 재생 구현
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Info.plist
  RelaxOn/Views/Home/CdLibraryView.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
Labels: feature

#146 [feat] CDLibrary에서 사용자의 music을 삭제할 수 있도록 구현
  RelaxOn/Manager/UserDefaultsManager.swift
  RelaxOn/Model/DummyData.swift
  RelaxOn/Model/MixedSound.swift
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/CustomAlertView.swift
Labels: feature, fix

#149 [Feature]: #126 무음 모드에서 소리 재생
  RelaxOn/Manager/AudioManager.swift
Labels: feature

#137 [Feat] #109 Main 뷰 Hi-fi 씌우기
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/CdLibraryView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
Labels: feature

#143 [Feature]: #136 스몰 위젯 구현
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Manager/WidgetManager.swift
  RelaxOn/Model/MixedSound.swift
  RelaxOn/Model/Sound.swift
  RelaxOn/RelaxOn.entitlements
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/HomeView.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOn/Views/Kitchen/KitchenView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOnWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  RelaxOnWidget/Assets.xcassets/Contents.json
  RelaxOnWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  RelaxOnWidget/CDWidgetEntry.swift
  RelaxOnWidget/Info.plist
  RelaxOnWidget/Provider.swift
  RelaxOnWidget/RelaxOnWidget.intentdefinition
  RelaxOnWidget/RelaxOnWidget.swift
  RelaxOnWidgetExtension.entitlements
Labels: feature

#154 [Feature]: 타이머 뷰 hifi 씌우기
  RelaxOn/Views/Home/Timer/TimerNavigationLinkView.swift
  RelaxOn/Views/Home/Timer/TimerPickerView.swift
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
Labels: feature

#157 [feat] 타이머로 사용자 음악을 종료
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Manager/TimerManager.swift
  RelaxOn/Model/MusicTimer.swift
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
Labels: feature

#150 [Feature]: #135 영어 → 한국어 다국어 지원
  RelaxOn/Model/Sound.swift
  RelaxOn/Utilities/Extension.swift
  RelaxOn/Utilities/en.lproj/Localizable.strings
  RelaxOn/Utilities/ko.lproj/Localizable.strings
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
  RelaxOn/Views/Kitchen/SoundCardView.swift
Labels: feature

#153 [Fix]: #152 App logo 변경
  RelaxOn/Assets.xcassets/AppIcon.appiconset/100.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/1024.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/114.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/120.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/128.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/144.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/152.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/16.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/167.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/172.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/180.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/196.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/20.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/216.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/256.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/29.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/32.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/40.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/48.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/50.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/512.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/55.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/57.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/58.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/60.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/64.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/72.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/76.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/80.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/87.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/88.png
  RelaxOn/Assets.xcassets/AppIcon.appiconset/Contents.json
  RelaxOn/Assets.xcassets/SplashImage.imageset/Contents.json
  RelaxOn/Assets.xcassets/SplashImage.imageset/SplashImage.png
  RelaxOn/Launch Screen.storyboard
Labels: fix

#147 [Feature]: #125 Studio 뷰 내에서 material 볼륨 조절
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Utilities/Extension.swift
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Kitchen/VolumeSlider.swift
Labels: feature

#155 [Feat] #114 : 워치 앱 로직 구현
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOnWatch WatchKit Extension/ComplicationController.swift
  RelaxOnWatch WatchKit Extension/Connectivity.swift
  RelaxOnWatch WatchKit Extension/Info.plist
  RelaxOnWatch WatchKit Extension/NotificationController.swift
  RelaxOnWatch WatchKit Extension/NotificationView.swift
  RelaxOnWatch WatchKit Extension/PlayerView.swift
  RelaxOnWatch WatchKit Extension/PlayerViewModel.swift
  RelaxOnWatch WatchKit Extension/Preview Content/Preview Assets.xcassets/Contents.json
  RelaxOnWatch WatchKit Extension/PushNotificationPayload.apns
  RelaxOnWatch WatchKit Extension/RelaxOnApp.swift
  RelaxOnWatch/Assets.xcassets/AccentColor.colorset/Contents.json
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/Contents.json
  RelaxOnWatch/Assets.xcassets/Contents.json
Labels: feature

#162 [Feat] #108 : Material 일러스트 작업
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOn.xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Assets.xcassets/Illust/BaseIllust.imageset/Contents.json
  RelaxOn/Assets.xcassets/Illust/BaseIllust.imageset/base.png
  RelaxOn/Assets.xcassets/Illust/Contents.json
  RelaxOn/Assets.xcassets/Illust/MelodyIllust.imageset/Contents.json
  RelaxOn/Assets.xcassets/Illust/MelodyIllust.imageset/melody.png
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Kitchen/SelectedImageView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Onboarding/OnboardingView.swift
Labels: feature

#163 워치 아이콘 추가하고 release/2.0.0 빌드 시 재생 문제 해결
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/100.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/1024.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/172.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/196.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/216.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/48.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/55.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/58.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/80.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/87.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/88.png
  RelaxOnWatch/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: fix

#168 [Feat] Preview 여러개 볼 수 있도록 구현
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Utilities/MultiPreview.swift
  RelaxOn/Views/Home/CdLibraryView.swift
Labels: feature

#167 [Refactor] 사용하지 않는 코드 제거
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Manager/UserDefaultsManager.swift
  RelaxOn/Views/CustomTabView.swift
  RelaxOn/Views/Home/CdLibraryView.swift
  RelaxOn/Views/Home/HomeView.swift
  RelaxOn/Views/Home/MixedSoundCardView.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Kitchen/CustomAlertView.swift
  RelaxOn/Views/Kitchen/KitchenView.swift
  RelaxOn/Views/Kitchen/SoundCardView.swift
  RelaxOn/Views/Onboarding/OnboardingView.swift
Labels: refactor

#192 [feat] #173 추가된 일러스트 Material 추가
  RelaxOn/Assets.xcassets/Sound thumbnail/Base/LongSun.imageset/LongSun.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Base/Oxygen.imageset/Oxygen.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Base/SpaceHigh.imageset/SpaceHigh.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Base/SpaceLow.imageset/SpaceLow.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Base/SpaceMid.imageset/SpaceMid.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Melody/Ambient.imageset/Ambient.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Melody/Garden.imageset/Contents.json
  RelaxOn/Assets.xcassets/Sound thumbnail/Melody/Garden.imageset/Garden.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Melody/Garden.imageset/PeacefulGarden.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Melody/Gymnopedia.imageset/Gymnopedie.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Melody/Relaxing.imageset/Relaxing.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Melody/Wisdom.imageset/Wisdom.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Natural/DryGrass.imageset/DryGrass.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Natural/Stream.imageset/Stream.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Natural/SummerField.imageset/SummerField.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Natural/UmbrellaRain.imageset/UmbrellaRain.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Natural/Wave.imageset/Wave.png
Labels: feature

#185 [Feat] #171 스튜디오 뷰 내, 볼륨 조절 및 기타 에러 수정
  RelaxOn/Views/Kitchen/SelectedImageView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
Labels: feature

#189 [refact] : Code Refactoring
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Extension/Color+Extension.swift
  RelaxOn/Extension/String+Extension.swift
  RelaxOn/Extension/UIColor+Extension.swift
  RelaxOn/Extension/View+Extension.swift
  RelaxOn/Manager/UserDefaultsManager.swift
  RelaxOn/Manager/WidgetManager.swift
  RelaxOn/Model/MixedSound.swift
  RelaxOn/RelaxOn.entitlements
  RelaxOn/Utilities/Extension.swift
  RelaxOn/Utilities/Static.swift
Labels: refactor

#190 [refact] : Update UserDefaultManager
  RelaxOn/Manager/UserDefaultsManager.swift
  RelaxOn/Model/MixedSound.swift
  RelaxOn/Views/Home/CdLibraryView.swift
  RelaxOn/Views/Home/Music/MusicRenameView.swift
  RelaxOn/Views/Home/Music/NewMusicView.swift
  RelaxOn/Views/Home/Music/VolumeControlView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/StudioNamingView.swift
  RelaxOn/Views/Onboarding/OnboadingNamingView.swift
  RelaxOn/Views/Onboarding/OnboardingFinishView.swift
Labels: refactor

#194 [fix] 타이머 관련 버그 수정
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Manager/TimerManager.swift
  RelaxOn/Views/Home/Timer/TempMainView.swift
  RelaxOn/Views/Home/Timer/TimerNavigationLinkView.swift
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
Labels: fix

#191 [ refact] : Onboarding & Kitchen View
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Extension/Float+Extension.swift
  RelaxOn/Extension/View+Extension.swift
  RelaxOn/Utilities/Extension.swift
  RelaxOn/Views/Home/Music/NewMusicView.swift
  RelaxOn/Views/Home/Music/VolumeControlView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
  RelaxOn/Views/Kitchen/RadioButtonGroupView.swift
  RelaxOn/Views/Kitchen/RectPreference.swift
  RelaxOn/Views/Kitchen/SelectedImageBackgroundView.swift
  RelaxOn/Views/Kitchen/SelectedImageView.swift
  RelaxOn/Views/Kitchen/SoundCardView.swift
  RelaxOn/Views/Kitchen/StudioNamingView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Kitchen/VolumeSlider.swift
  RelaxOn/Views/Onboarding/OnboadingNamingView.swift
  RelaxOn/Views/Onboarding/OnboardingFinishView.swift
  RelaxOn/Views/Onboarding/OnboardingView.swift
Labels: refactor

#196 [refact] : Audio Display Name
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Extension/String+Extension.swift
  RelaxOn/Model/Sound.swift
  RelaxOn/Utilities/Static.swift
Labels: refactor

#199 [Fix] empty Sound의 이미지 노출 수정
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/Music/NewMusicView.swift
Labels: fix

#186 [fix] id 생성 방법 변경
  RelaxOn/Model/DummyData.swift
  RelaxOn/Model/MixedSound.swift
  RelaxOn/Views/Home/Music/MusicRenameView.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/VolumeControlView.swift
  RelaxOn/Views/Kitchen/StudioNamingView.swift
  RelaxOn/Views/Onboarding/OnboadingNamingView.swift
Labels: fix

#202 [Feat] StudioView에서 음원 볼륨 저장
  RelaxOn/Views/Kitchen/StudioView.swift
Labels: feature

#207 [fix] localization text 수정
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Utilities/en.lproj/Localizable.strings
  RelaxOn/Utilities/ko.lproj/Localizable.strings
  RelaxOn/Views/Home/Music/VolumeControlView.swift
  RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
  RelaxOn/Views/Kitchen/StudioNamingView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Onboarding/OnboardingView.swift
Labels: fix

#203 [Feat] 타이머 종료되면 음악 종료되도록 수정
  RelaxOn/Views/Home/Music/NewMusicView.swift
Labels: feature

#210 [fix] Release 브랜치 에러 및 MusicView에서 볼륨 변경시 닫히는 오류 해결
  RelaxOn/Views/Home/CdLibraryView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOn/Views/Home/Music/VolumeControlView.swift
  RelaxOn/Views/Onboarding/OnboardingView.swift
Labels: bug

#212 [Bugfix] Volume Control시 NewMusicView가 꺼지는 현상 수정
  RelaxOn/Model/MixedSound.swift
  RelaxOn/Views/Home/Music/VolumeControlView.swift
Labels: fix
