Repository M1zz/RelaxOn, pull requests merged in 2022-09, with the labels that each got.

#214 [fix] albumCover 안뜨는 현상 수정
  RelaxOn/Views/Home/Music/MusicViewModel.swift
Labels: fix

#225 [fix] remoteController가 onboarding, kitchen music에 반응하지 않도록 설정
  RelaxOn/Views/Home/CdLibraryView.swift
  RelaxOn/Views/Home/Music/NewMusicView.swift
Labels: fix

#231 [fix] CDLibraryView에서 편집시 원크기 수정
  RelaxOn/Views/Kitchen/CDListView.swift
Labels: fix

#229 [Fix] StudioView에서 선택한 이미지가 보여지지 않고 하나의 이미지만 보여주던 현상 & 이미지 겹치는 부분에 opacity제거
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/Music/NewMusicView.swift
  RelaxOn/Views/Kitchen/SelectedImageView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Onboarding/OnboardingView.swift
Labels: fix

#240 [fix] CD제작중 메인화면으로 돌아갔을 때 음원이 멈추도록 수정
  RelaxOn/Views/Kitchen/StudioView.swift
Labels: fix

#239 [fix] : 버튼 비활성화 문제 해결
  RelaxOn/Views/Home/Music/MusicRenameView.swift
  RelaxOn/Views/Kitchen/StudioNamingView.swift
  RelaxOn/Views/Onboarding/OnboadingNamingView.swift
Labels: fix

#238 [fix] MusicNaming 관련 뷰들 UI수정
  RelaxOn/Views/Home/Music/MusicRenameView.swift
  RelaxOn/Views/Kitchen/StudioNamingView.swift
  RelaxOn/Views/Onboarding/OnboadingNamingView.swift
Labels: fix

#237 [fix] 베이스, 멜로디, 백색소음 탭 좌우정렬
  RelaxOn/Utilities/Static.swift
  RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
  RelaxOn/Views/Kitchen/RectPreference.swift
  RelaxOn/Views/Onboarding/OnboardingView.swift
Labels: fix

#233 [fix] 디자인 수정 반영
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Assets.xcassets/Sound thumbnail/Base/LongSun.imageset/LongSun.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Base/SpaceMid.imageset/SpaceMid.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Melody/Relaxing.imageset/Relaxing.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Melody/Wisdom.imageset/Wisdom.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Natural/Stream.imageset/Stream.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Natural/SummerField.imageset/SummerField.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Natural/UmbrellaRain.imageset/UmbrellaRain.png
  RelaxOn/Assets.xcassets/Sound thumbnail/Natural/Wave.imageset/Wave.png
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/Contents.json
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/DryGrass.imageset/Contents.json
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/DryGrass.imageset/DryGrass.png
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/Stream.imageset/Contents.json
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/Stream.imageset/Stream.png
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/SummerField.imageset/Contents.json
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/SummerField.imageset/SummerField.png
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/UmbrellaRain.imageset/Contents.json
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/UmbrellaRain.imageset/UmbrellaRain.png
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/Wave.imageset/Contents.json
  RelaxOn/Assets.xcassets/Sound thumbnail/WhiteNoise/Wave.imageset/Wave.png
  RelaxOn/Assets.xcassets/Widget/Contents.json
  RelaxOn/Assets.xcassets/Widget/WidgetBackground.imageset/Contents.json
  RelaxOn/Assets.xcassets/Widget/WidgetBackground.imageset/WidgetBackground.png
  RelaxOn/Assets.xcassets/Widget/WidgetLogo.imageset/Contents.json
  RelaxOn/Assets.xcassets/Widget/WidgetLogo.imageset/WidgetLogo.png
Labels: fix

#236 [fix] CD를 클릭했을 때도 위젯에 재생된 CD data가 저장되도록
  RelaxOn/Views/Home/Music/NewMusicView.swift
Labels: fix

#242 [fix] material에서 base만 누르고 다른 것들은 '선택 안함'도 누르지 않고 바로 만든 경우 생기는 버그
  RelaxOn/Manager/AudioManager.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
Labels: fix

#255 [Fix] #253 : 모든 CD 테두리 radius 값 추가
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Delegate/MusicViewDelegate.swift
  RelaxOn/Model/MixedSound.swift
  RelaxOn/Model/Sound.swift
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/CdLibraryView.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOn/Views/Home/Music/NewMusicView.swift
  RelaxOn/Views/Home/Music/VolumeControlView.swift
  RelaxOn/Views/Kitchen/CDCoverImageView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/CDNamingView.swift
  RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
  RelaxOn/Views/Kitchen/SelectedImageBackgroundView.swift
  RelaxOn/Views/Kitchen/SelectedImageView.swift
  RelaxOn/Views/Kitchen/SoundCardView.swift
  RelaxOn/Views/Kitchen/StudioNamingView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Onboarding/OnboardingFinishView.swift
  RelaxOn/Views/Onboarding/OnboardingView.swift
Labels: fix

#250 [Bug] #218 : 앨범 뒤에 깔리는 그림 비율 유지되어야 함(center crop)
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Views/Home/Music/MusicView.swift
Labels: bug, fix

#272 [feat] #268: Studio뷰로 넘어가는 뷰 수정
  RelaxOn/Views/Kitchen/CDListView.swift
Labels: feature

#259 [feat] #249 : 워치 앱 구현
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOnWatch WatchKit Extension/Complication/ComplicationController.swift
  RelaxOnWatch WatchKit Extension/Connectivity.swift
  RelaxOnWatch WatchKit Extension/ListView.swift
  RelaxOnWatch WatchKit Extension/Managers/CDPlayerManager.swift
  RelaxOnWatch WatchKit Extension/Managers/WatchConnectivityManager.swift
  RelaxOnWatch WatchKit Extension/Notification/NotificationController.swift
  RelaxOnWatch WatchKit Extension/Notification/NotificationView.swift
  RelaxOnWatch WatchKit Extension/Notification/PushNotificationPayload.apns
  RelaxOnWatch WatchKit Extension/PlayerViewModel.swift
  RelaxOnWatch WatchKit Extension/RelaxOnApp.swift
  RelaxOnWatch WatchKit Extension/TabsView.swift
  RelaxOnWatch WatchKit Extension/Views/CDListView.swift
  RelaxOnWatch WatchKit Extension/Views/CDPlayerView.swift
  RelaxOnWatch WatchKit Extension/Views/PageView.swift
Labels: feature

#258 [refactor] 오타 수정
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
Labels: refactor

#257 [refact] #256 : CD 만드는 View 합치기
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/CDNamingView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Onboarding/OnboardingView.swift
Labels: refactor

#271 [refactor] #236 : Sound Empty 코드 개선
  RelaxOn/Model/Sound.swift
Labels: refactor

#266 [feat] 음악 재생화면 디자인 수정
  RelaxOn/Views/Home/Music/MusicView.swift
Labels: feature

#267 [feat]: 음악 정렬 순서 변경
  RelaxOn/Views/Kitchen/CDListView.swift
Labels: feature

#274 [fix] localization 수정
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Utilities/en.lproj/Localizable.strings
  RelaxOn/Utilities/ko.lproj/Localizable.strings
Labels: fix

#278 [fix]: #277 영문키보드만 가능하던 부분 수정
  RelaxOn/Views/Kitchen/CDNamingView.swift
Labels: fix

#276 [fix] #269 segmentControl 하단 바 크기 수정 및 정렬 수정
  RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
Labels: fix

#281 [Fix] #280 : CD 제작 시, CD Cover Image의 Background 색상 변경
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Kitchen/CDCoverImageView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
Labels: fix

#270 [Feature] #262 : Onboarding View의 저장 후 화면 전환 효과 추가
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Views/Kitchen/CDCoverImageView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/CDNamingView.swift
  RelaxOn/Views/Onboarding/OnboardingFinishView.swift
Labels: feature

#279 [feat] #260 : 워치로 음악 볼륨 조절 기능 구현
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOn/Views/Kitchen/VolumeSliderView.swift
  RelaxOnWatch WatchKit Extension/Managers/CDPlayerManager.swift
  RelaxOnWatch WatchKit Extension/Managers/WatchConnectivityManager.swift
  RelaxOnWatch WatchKit Extension/Views/CDPlayerView.swift
Labels: feature

#284 [Fix] #283: CDNamingView에서 UI가 중복되어 표시되는 현상
  RelaxOn/Views/Kitchen/CDNamingView.swift
Labels: fix

#287 [fix] #285 widget asset 경로 꼬임 해결
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/App/Assets/Widget.xcassets/Contents.json
  RelaxOn/App/Assets/Widget.xcassets/Widget/Contents.json
  RelaxOnWidget/Assets.xcassets/SystemGrey1.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/WidgetBackground.imageset/Contents.json
  RelaxOnWidget/Assets.xcassets/WidgetBackground.imageset/WidgetBackground.png
  RelaxOnWidget/Assets.xcassets/WidgetLogo.imageset/Contents.json
  RelaxOnWidget/Assets.xcassets/WidgetLogo.imageset/WidgetLogo.png
Labels: fix

#290 [feat] lockScreenWidget을 구현하였습니다.
  LockScreenWidgetExtension/Assets.xcassets/AccentColor.colorset/Contents.json
  LockScreenWidgetExtension/Assets.xcassets/AppIcon.appiconset/Contents.json
  LockScreenWidgetExtension/Assets.xcassets/Contents.json
  LockScreenWidgetExtension/Assets.xcassets/WidgetBackground.colorset/Contents.json
  LockScreenWidgetExtension/Assets.xcassets/WidgetLogo.imageset/Contents.json
  LockScreenWidgetExtension/Assets.xcassets/WidgetLogo.imageset/WidgetLogo.png
  LockScreenWidgetExtension/Info.plist
  LockScreenWidgetExtension/LockScreenWidgetExtension.swift
  LockScreenWidgetExtensionExtension.entitlements
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/App/SceneDelegate.swift
  RelaxOn/Manager/WidgetManager.swift
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/Timer/TimerNavigationLinkView.swift
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
  WatchOSLockScreenWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  WatchOSLockScreenWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  WatchOSLockScreenWidget/Assets.xcassets/Contents.json
  WatchOSLockScreenWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  WatchOSLockScreenWidget/Assets.xcassets/WidgetLogo.imageset/Contents.json
  WatchOSLockScreenWidget/Assets.xcassets/WidgetLogo.imageset/WidgetLogo.png
  WatchOSLockScreenWidget/Info.plist
  WatchOSLockScreenWidget/WatchOSLockScreenWidget.swift
  WatchOSLockScreenWidgetExtension.entitlements
Labels: feature

#291 [feat] 타이머 뷰 추가, 버그 수정
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Manager/TimerManager.swift
  RelaxOn/Views/Home/Timer/CustomNavigationLink.swift
  RelaxOn/Views/Home/Timer/TimerNavigationLinkView.swift
  RelaxOn/Views/Home/Timer/TimerProgressBarView.swift
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
Labels: fix

#292 [fix] 타이머 시간 피커 배경화면 변경
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
Labels: fix

#293 [feat] 타이머 cancel 기능 추가
  RelaxOn/Manager/TimerManager.swift
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
Labels: feature

#295 [fix] widget Image 수정
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOnWidget/Assets.xcassets/Colors/Background.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/ButtonBackground.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/Forground.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/LaunchBackground.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/Main Colors/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/Main Colors/RelaxBlack.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/Main Colors/RelaxDimPurple.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/Main Colors/RelaxLavender.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/Main Colors/RelaxNightBlue.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/Main Colors/RelaxRealBlack.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/System Colors/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/System Colors/SystemGrey1.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/System Colors/SystemGrey2.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/System Colors/SystemGrey3.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/TabBackground.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Colors/TextGray.colorset/Contents.json
  RelaxOnWidget/Assets.xcassets/Sound thumbnail/Base/LongSun.imageset/LongSun.png
  RelaxOnWidget/Assets.xcassets/Sound thumbnail/Melody/PeacefulGarden.imageset/Contents.json
  RelaxOnWidget/Assets.xcassets/Sound thumbnail/Melody/PeacefulGarden.imageset/PeacefulGarden.png
  RelaxOnWidget/Assets.xcassets/Widget/Contents.json
  RelaxOnWidget/Assets.xcassets/Widget/WidgetBackground.imageset/Contents.json
  RelaxOnWidget/Assets.xcassets/Widget/WidgetBackground.imageset/WidgetBackground.png
  RelaxOnWidget/Assets.xcassets/Widget/WidgetLogo.imageset/Contents.json
  RelaxOnWidget/Assets.xcassets/Widget/WidgetLogo.imageset/WidgetLogo.png
Labels: fix

#297 [feat] 타이머 캔슬시 락스크린 초기화
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
Labels: feature

#299 [fix] 뮤직뷰에서 볼륨이 한 번에 조절되는 현상 수정
  RelaxOn/Model/SoundType.swift
Labels: fix

#301 [fix] MusicView에서 볼륨을 조절할 때 의도하지 않은 애니메이션이 적용되던 현상 수정
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/VolumeControlView.swift
Labels: fix

#303 [fix] CDLibrary에서 음원 delete시 delete 상태가 바로 적용되지 않던 현상 수정
  RelaxOn/Views/Kitchen/CDListView.swift
Labels: fix

#305 [fix] studio에서 입력한 볼륨과 실제 생성된 볼륨이 다른 현상 & 앱내 컨트롤러 오류 수정
  RelaxOn/Model/SoundType.swift
  RelaxOn/Views/Kitchen/CDListView.swift
Labels: fix

#309 [fix] musicView & 앱내 컨트롤러 오류 수정
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOn/Views/Kitchen/StudioView.swift
Labels: fix

#311 [fix] emptySoun를 .base 타입으로 생성하여 생기는 오류
  LockScreenWidgetExtension/LockScreenWidgetExtension.swift
  RelaxOn/Model/MixedSound.swift
  RelaxOn/Model/Sound.swift
  RelaxOn/Model/SoundType.swift
  RelaxOn/Views/Kitchen/SoundCardView.swift
Labels: fix

#313 [feat] #312 : SwiftLint 적용 및 파일 추가
  .swiftlint.yml
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
Labels: feature

#317 [fix] swiftLint 에러 수정
  .swiftlint.yml
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
  RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
  RelaxOn/Manager/WidgetManager.swift
  RelaxOn/Utilities/Static.swift
  RelaxOn/Utilities/ViewModifiers.swift
  RelaxOn/Views/Home/Music/CDLibraryMusicController.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOn/Views/Home/Timer/TimerSettingView.swift
  RelaxOn/Views/Kitchen/CDNamingView.swift
  RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
  RelaxOn/Views/Kitchen/RadioButtonGroupView.swift
  RelaxOn/Views/Kitchen/SoundCardView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Onboarding/OnboardingFinishView.swift
  RelaxOnWidget/CDWidgetEntry.swift
  RelaxOnWidget/RelaxOnWidget.swift
Labels: fix

#319 [Refactor] Widget refactoring
  LockScreenWidgetExtension/LockScreenWidgetExtension.swift
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/App/AppDelegate.swift
  RelaxOn/App/RelaxOnApp.swift
  RelaxOn/App/SceneDelegate.swift
  RelaxOn/Manager/WidgetManager.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOn/Views/Kitchen/CDCoverImageView.swift
  RelaxOnWidget/Assets.xcassets/Sound thumbnail/Melody/Garden.imageset/Contents.json
  RelaxOnWidget/Assets.xcassets/Sound thumbnail/Melody/Garden.imageset/PeacefulGarden.png
  RelaxOnWidget/Provider.swift
  RelaxOnWidget/RelaxOnWidget.swift
Labels: refactor

#321 [Refactor] MusicView & MusicViewModel 를 refactoring 하였습니다.
  RelaxOn/Model/Sound.swift
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/CdLibraryView.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/MusicViewModel.swift
  RelaxOn/Views/Home/Music/VolumeControlView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/CDNamingView.swift
  RelaxOn/Views/Onboarding/OnboardingFinishView.swift
  RelaxOnWidget/CDWidgetEntry.swift
  RelaxOnWidget/RelaxOnWidget.swift
Labels: refactor

#323 [Refactor] MusicController를 컴포넌트화 하였습니다. #321 리뷰가 끝난뒤에 리뷰해주세요!
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/Views/Home/CDCardView.swift
  RelaxOn/Views/Home/Music/CDLibraryMusicController.swift
  RelaxOn/Views/Home/Music/Component/MusicController.swift
  RelaxOn/Views/Home/Music/MusicView.swift
  RelaxOn/Views/Home/Music/VolumeControlView.swift
  RelaxOn/Views/Kitchen/CDListView.swift
  RelaxOn/Views/Kitchen/CDNamingView.swift
  RelaxOn/Views/Kitchen/StudioView.swift
  RelaxOn/Views/Onboarding/OnboardingFinishView.swift
Labels: refactor

#327 [fix] #326 : Change Xcode Version in GitAction
  .github/workflows/ios.yml
Labels: fix
