Repository M1zz/RelaxOn, pull requests merged in 2022-07, with the labels that each got.

#46 [docs] #45 : README.md 추가
  README.md
  Release-Note.md
Labels: documentation

#39 [fix]: #38 WhiteTitleText를 struct가 아닌 ViewModifier로 구현
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe/Model/DummyData.swift
  LullabyRecipe/Utilities/ViewModifiers.swift
  LullabyRecipe/Views/Home/Home.swift
  LullabyRecipe/Views/Home/Music/Music.swift
  LullabyRecipe/Views/Home/Music/VolumeControl.swift
  LullabyRecipe/Views/Kitchen/Kitchen.swift
  LullabyRecipe/Views/Onboarding/OnBoarding.swift
  LullabyRecipe/Views/WhiteTitleText.swift
Labels: fix

#67 [fix] #66 Sound에 존재하는 MixedSound 제거
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe/Model/Sound.swift
Labels: fix

#30 [feature]: #26 다국어 지원 세팅
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe/Model/DummyData.swift
  LullabyRecipe/Utilities/en.lproj/Localizable.strings
  LullabyRecipe/Utilities/ko.lproj/Localizable.strings
Labels: feature

#69 [docs]: Refactoring Template 깃 경로 설정 변경 및 추가 작업
  .github/ISSUE_TEMPLATE/Refactoring_Template
Labels: documentation, fix

#54 [feature]: PR을 올렸을 때 자동으로 리뷰어 만들기
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/feature-issue-template.yml
Labels: documentation

#71 [Fix]: #63 shared 삭제
  LullabyRecipe/Manager/AudioManager.swift
Labels: fix

#78 [Fix]: #77 color name 변경
  LullabyRecipe/Views/CustomTabView.swift
Labels: fix

#76 [Fix]: #73 함수 래핑
  LullabyRecipe/Manager/AudioManager.swift
Labels: fix

#83 [fix] 파일 확장자 지정되지않아 템플릿 적용 안되는 문제 수정
  .github/ISSUE_TEMPLATE/Refactoring_Template.yml
Labels: fix

#87 [feat] #81 StudioView 뷰 작업
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe.xcodeproj/project.xcworkspace/xcuserdata/kim-yeonho.xcuserdatad/UserInterfaceState.xcuserstate
  LullabyRecipe/Utilities/Static.swift
  LullabyRecipe/Views/Kitchen/CustomSegmentControlView.swift
  LullabyRecipe/Views/Kitchen/RectPreference.swift
  LullabyRecipe/Views/Kitchen/SoundCard.swift
  LullabyRecipe/Views/Kitchen/StudioView.swift
Labels: feature

#80 [docs] #79 : Create Git Action File
  .github/workflows/ios.yml
Labels: undefined

#86 [Fix]: #72 View 이름 변경
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe/CdLibraryView.swift
  LullabyRecipe/LullabyRecipeApp.swift
  LullabyRecipe/Views/CustomTabView.swift
  LullabyRecipe/Views/Home/HomeView.swift
  LullabyRecipe/Views/Home/MixedSoundCardView.swift
  LullabyRecipe/Views/Home/Music/MusicView.swift
  LullabyRecipe/Views/Home/Music/VolumeControlView.swift
  LullabyRecipe/Views/Kitchen/CustomAlertView.swift
  LullabyRecipe/Views/Kitchen/KitchenView.swift
  LullabyRecipe/Views/Kitchen/SoundCardView.swift
  LullabyRecipe/Views/Kitchen/StudioView.swift
  LullabyRecipe/Views/Onboarding/OnboardingView.swift
Labels: fix

#92 [refactor]: #91 사용하지 않는 코드 제거
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe/Model/Recipe.swift
  LullabyRecipe/Model/Sound.swift
  LullabyRecipe/Views/Kitchen/CustomAlertView.swift
Labels: refactor

#98 #89, #90 Material 일러스트 레이어링
  LullabyRecipe/Utilities/ViewModifiers.swift
  LullabyRecipe/Views/Kitchen/StudioView.swift
Labels: feature

#100 [Feat] forced unwrapped 삭제
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe/Manager/AudioManager.swift
  LullabyRecipe/Model/Sound.swift
  LullabyRecipe/Views/Home/MixedSoundCardView.swift
  LullabyRecipe/Views/Home/Music/MusicView.swift
  LullabyRecipe/Views/Home/Music/VolumeControlView.swift
  LullabyRecipe/Views/Kitchen/CustomAlertView.swift
Labels: refactor

#102 [FEAT] 타이머 화면 구현
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe/Views/Home/Timer/TempMainView.swift
  LullabyRecipe/Views/Home/Timer/TimerNavigationLinkView.swift
  LullabyRecipe/Views/Home/Timer/TimerPickerView.swift
  LullabyRecipe/Views/Home/Timer/TimerSettingView.swift
Labels: feature

#104 [Feat] #94, #95 CDLibraryView 관련 뷰들 작성 및 StudioView, Timer UI 뷰와 연결
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe/CdLibraryView.swift
  LullabyRecipe/Views/Home/CDCardView.swift
  LullabyRecipe/Views/Kitchen/CDListView.swift
  LullabyRecipe/Views/Kitchen/StudioView.swift
Labels: feature

#103 [Feat] Material 믹싱 완료 버튼 및 NavigationBar 구현
  LullabyRecipe.xcodeproj/project.pbxproj
  LullabyRecipe.xcodeproj/project.xcworkspace/xcuserdata/kim-yeonho.xcuserdatad/UserInterfaceState.xcuserstate
  LullabyRecipe/Utilities/Static.swift
  LullabyRecipe/Views/Kitchen/CustomAlertView.swift
  LullabyRecipe/Views/Kitchen/CustomSegmentControlView.swift
  LullabyRecipe/Views/Kitchen/KitchenView.swift
  LullabyRecipe/Views/Kitchen/StudioView.swift
  LullabyRecipe/Views/Kitchen/TestNavigateView.swift
Labels: feature
