Repository M1zz/RelaxOn, pull requests merged in 2023-05, with the labels that each got.

#393 ➕[Add]: Color Assets 추가
  RelaxOn.xcodeproj/project.pbxproj
  RelaxOn/App/Assets/RenewAssets.xcassets/AnyDarkBackgroundColor.colorset/Contents.json
  RelaxOn/App/Assets/RenewAssets.xcassets/Contents.json
  RelaxOn/App/Assets/RenewAssets.xcassets/PrimaryPurple.colorset/Contents.json
Labels: prepare

#408 🐛[Fix]: CircularSlider + Timer UI
  RelaxOn/App/Assets/RenewAssets.xcassets/Icon/SoundDetail/headphone.imageset/headphone.png
  RelaxOn/App/Assets/RenewAssets.xcassets/Icon/SoundDetail/headphone.imageset/headphone@2x.png
  RelaxOn/App/Assets/RenewAssets.xcassets/Icon/SoundDetail/headphone.imageset/headphone@3x.png
  RelaxOn/App/Assets/RenewAssets.xcassets/Icon/SoundDetail/headset.imageset/Contents.json
  RelaxOn/App/Assets/RenewAssets.xcassets/Icon/SoundDetail/headset.imageset/headset.svg
  RelaxOn/App/Assets/RenewAssets.xcassets/Icon/SoundDetail/pitch.imageset/Contents.json
  RelaxOn/App/Assets/RenewAssets.xcassets/Icon/SoundDetail/pitch.imageset/pitch.png
  RelaxOn/App/Assets/RenewAssets.xcassets/Icon/SoundDetail/pitch.imageset/pitch.svg
  RelaxOn/App/Manager/TimerManager.swift
  RelaxOn/App/Utils/Enums.swift
  RelaxOn/App/Views/Components/CircularSlider.swift
  RelaxOn/App/Views/Components/TimerProgressView.swift
  RelaxOn/App/Views/Home/SoundDetailView.swift
Labels: 마감임박

#413 🎨[Design]: LaunchScreen 변경
  RelaxOn/App/Assets/RenewAssets.xcassets/LaunchScreen.imageset/Contents.json
  RelaxOn/App/Assets/RenewAssets.xcassets/LaunchScreen.imageset/LaunchScreen.png
  RelaxOn/App/Assets/RenewAssets.xcassets/LaunchScreen.imageset/LaunchScreen.svg
  RelaxOn/App/Assets/RenewAssets.xcassets/LaunchScreen.imageset/LaunchScreen@2x.png
  RelaxOn/App/Assets/RenewAssets.xcassets/LaunchScreen.imageset/LaunchScreen@3x.png
  RelaxOn/Launch Screen.storyboard
Labels: 마감임박

#410 ✨ [Feat]: #409 Timer Pause/Resume
  RelaxOn/App/Assets/RenewAssets.xcassets/Button/button_pause.imageset/Contents.json
  RelaxOn/App/Assets/RenewAssets.xcassets/Button/button_pause.imageset/pause.svg
  RelaxOn/App/Manager/TimerManager.swift
  RelaxOn/App/Utils/Common.swift
  RelaxOn/App/Utils/Enums.swift
  RelaxOn/App/Views/Timer/TimerMainView.swift
Labels: feature
